# Generated by Django 3.0.4 on 2020-03-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='user_to',
            new_name='use_to',
        ),
    ]
